### ISSUE TITLE
Unable to use ES6 in Components

### ISSUE THREAD

**Issue by kjschulz** [magalhas/express-react-engine#15]
This is a cool little repo, just started using it and was excited to see that support was added to use ES6 but I'm not able to do so, I get errors upon every attempt.  Would you mind to either tell me or show me an example of what is needed outside the `.jsx` component in order to make babel work? (ie a .babelrc, presets, etc...I would have thought those would all be requirements of this repo and not my project but maybe that's what I'm missing)?

**Comment by magalhas** [comment]
This should be fixed by #17. I'll release a patch with it soon!

**Comment by kjschulz** [comment]
Thanks @magalhas , I'll look for the official patch but I can confirm that manually updating my copy to use https://github.com/magalhas/express-react-engine/pull/17 does indeed fix the issue 👍
